### ISSUE TITLE
Map: Fill in actual state results links in the copy spreadsheet

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#107]
After #97 is taken care of

**Comment by lindamood** [comment]
and create a jinja template that can loop through the state nav

**Comment by alykat** [comment]
Needs to be pointed to the new nav links spreadsheet. (This is for click-throughs on the results map and the drop-down that appears under the map for users on mobile, not the navbar. Ideally it should point to the same spreadsheet the nav does, though.)
