### ISSUE TITLE
State results: "null None of these candidates" and NPD in Nevada results

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#124]
Should probably remove the "null"? Also, what does "NPD" mean? 3 candidates (plus the null one) have that designation.

![image](https://cloud.githubusercontent.com/assets/491318/19878746/e43e074a-9fc2-11e6-9688-6da3a84fdb7e.png)

**Comment by TylerFisher** [comment]
This is fixed with the latest data bump
