### ISSUE TITLE
Override CSS to get global nav on story page

### ISSUE THREAD

**Issue by lindamood** [nprapps/elections16graphics#13]
If we want the global nav to live above the headline, we need to add override CSS to all the pages that nav will live on.
![election-site-map](https://cloud.githubusercontent.com/assets/1319852/19364199/3548b430-915b-11e6-8863-f353e7140d56.png)

**Comment by alykat** [comment]
Done in f0e6f83ae2b1f626962f191e07904e38e8952b46

**Comment by lindamood** [comment]
There's some top padding in the content well when the nav switches to the mobile breakpoint that I'd like to remove, if possible.
