### ISSUE TITLE
Update new factlist/quotable template with final assets

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections16graphics#136]
Do this Monday night/Tuesday morning so we don't accidentally use the theme

**Comment by eads** [comment]
Final assets ready and committed.

**Comment by eads** [comment]
![factlist-what-we-know](https://cloud.githubusercontent.com/assets/634572/19954421/a1ddbac0-a14e-11e6-9eff-9738edb50d1c.png)

![quote-what-then-is-time-if](https://cloud.githubusercontent.com/assets/634572/19954456/d8d21652-a14e-11e6-824c-73b188c68383.png)

@lindamood can you review these?

**Comment by alykat** [comment]
It's throwing me a little that the logos are bottom-aligned rather than center-aligned. Possible to nudge the NPR Politics logo down just a couple pixels so they're more vertically centered?

![image](https://cloud.githubusercontent.com/assets/491318/19955485/25752126-a158-11e6-8dfd-c126fc003a4a.png)

**Comment by lindamood** [comment]
Yes, @alykat good call. In addition, we would like to swap out the Color NPR politics logo with a gray one. @eads The gray logo lives in the eps file Meg sent via slack.

<img width="177" alt="slack_-_npr_digital" src="https://cloud.githubusercontent.com/assets/1319852/19966863/0a663900-a1a4-11e6-96e1-8fe501d6a341.png">

**Comment by eads** [comment]
I will make the tweaks this afternoon!

**Comment by eads** [comment]
Ok, new ones!

![quote-like-our-bodies-and-like](https://cloud.githubusercontent.com/assets/634572/19982409/5d9750a4-a1dc-11e6-8813-fe77f293c24c.png)

![quote-how-i-wished-during-those](https://cloud.githubusercontent.com/assets/634572/19982412/5f43bf5a-a1dc-11e6-80ae-d5342266a12d.png)

@alykat @lindamood do you think we should make the logos a little smaller in the 16x9 version?

**Comment by eads** [comment]
![quote-we-learn-from-history-as](https://cloud.githubusercontent.com/assets/634572/19982732/9fbbfdc6-a1dd-11e6-8507-b6aeb6a3923e.png)

**Comment by eads** [comment]
![quote-a-man-may-be-in](https://cloud.githubusercontent.com/assets/634572/19982873/22098bd6-a1de-11e6-959c-04ccd5898652.png)

**Comment by lindamood** [comment]
@eads yes, I'd reduce the logo size slightly. I can pair on this with you, if you want.

**Comment by eads** [comment]
Ready to go! Closing in favor of a launch todo.
