### ISSUE TITLE
Document how to create a state Seamus page

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections16graphics#137]
- How to do the include
- SEO requirements (headline, window title, teaser)

**Comment by eads** [comment]
Still waiting on final SEO reqs

**Comment by eads** [comment]
[Here's a draft](https://docs.google.com/document/d/1sRL-WuzzqbHUeeAp71Y4l2UW7D7mYRygCMHG_J9CLZ8/edit), awaiting final review and confirmation.
