### ISSUE TITLE
Test override css on Seamus big board page

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#155]
Seeing some weird overlaps. I wonder if we should hide the site footer and replicate the links at the bottom of our boards.

![image](https://cloud.githubusercontent.com/assets/491318/19946200/c3678ffc-a119-11e6-8f55-d7edff43e3c2.png)

**Comment by eads** [comment]
The player tray opens partially obscured by window boundary.

![menu slides off screen](https://www.dropbox.com/s/5xq1g9d6byb0f1s/Screenshot%202016-11-06%2009.00.16.png?dl=1)

**Comment by eads** [comment]
Re-prioritized critical. The critical part is making some choices so that nothing looks broken.

**Comment by eads** [comment]
Related to #190
