### ISSUE TITLE
Spot-check county data

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#161]
Make sure what we're displaying for unemployment, past results, etc., matches up.

**Comment by ClintonKing** [comment]
2012 results for Mass might be wrong? Checking other states, but haven't seen the same issue anywhere else yet.

**Comment by TylerFisher** [comment]
Hmmm, this might be an old township vs. county issue. Might need to recalculate them.

**Comment by TylerFisher** [comment]
Check Vermont/New Hampshire/Connecticut/Maine

**Comment by ClintonKing** [comment]
They're all off.

**Comment by TylerFisher** [comment]
Gonna take one more pass over this over the weekend, but I think it's good after the fix above

**Comment by TylerFisher** [comment]
Everything looks right now, checked a whole bunch of counties.
