### ISSUE TITLE
graphics sometimes get clipped navigating around

### ISSUE THREAD

**Issue by eads** [nprapps/elections16graphics#168]
<img width="826" alt="screenshot 2016-11-04 08 06 13" src="https://cloud.githubusercontent.com/assets/634572/20004964/be91e34a-a265-11e6-91c9-86673dc9845f.png">

**Comment by eads** [comment]
Specifically, when going back.
- Go to http://www-s1.npr.org/2016/11/04/500360280/test-new-results-nav
- Click "senate"
- Click back button

**Comment by TylerFisher** [comment]
eek. Is this a pym/pjax issue?

**Comment by TylerFisher** [comment]
Using the real URL with the date and slug fixes this. This means that the slugs **cannot** change throughout the night, or the nav will break.
