### ISSUE TITLE
Liveblog headline widget: Relative timestamps aren't auto-updating

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#177]
Has been at "10 seconds ago" for a couple minutes

![image](https://cloud.githubusercontent.com/assets/491318/20017553/8c0ebfda-a29a-11e6-88c4-1c4d2a80ef51.png)

When I refresh the page, the timestamps update as expected

**Comment by TylerFisher** [comment]
Fixed in 11267b0b165229af0ccb855195a8d2a942b1e79d
