### ISSUE TITLE
style liveblog BOP

### ISSUE THREAD

**Issue by eads** [nprapps/elections16graphics#198]

**Comment by katiepark** [comment]
I'm going to work on this today and we can check in Monday AM to see what's working/not working and what still needs to be done.

**Comment by katiepark** [comment]
Running to-do list for my brain's sake:
- [x] Move seat counts below bars
- [x] Change counts to reflect total "Expected" only
- [x] Double-check all math with Aly
- [x] Figure out whether lighter colors communicate the same correlation to "expected"
- [x] Check whether we need a source line on this "compact" view
- [ ] Stacked CSS for larger breakpoint (ah - this will be more complicated, we need the PARENT breakpoint. see how things look first as just one view)
- [x] On the live blog end -- float a right-aligned column for larger breakpoint
- [x] On the live blog end -- Reconsider placing BOPs below "Get Caught Up" headline
- [x] See if we need to incorporate this change in Aly's js: https://github.com/nprapps/elections16graphics/blob/master/www/js/includes/bop.js#L435-L461

**Comment by katiepark** [comment]
FYI, this is underway on this branch: https://github.com/nprapps/elections16graphics/tree/bop-liveblog

**Comment by katiepark** [comment]
Waiting on some feedback from Domenico but otherwise settled.

**Comment by katiepark** [comment]
Cleared with Domenico!
