### ISSUE TITLE
Nav: Is this the final branding?

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#203]
![image](https://cloud.githubusercontent.com/assets/491318/20043005/a453568c-a452-11e6-849f-1e126fbd13f3.png)

Or are we updating it to match what Meg's doing for social?

**Comment by lindamood** [comment]
I'll check in with the politics team on this.

**Comment by lindamood** [comment]
I updated the colors to match the social card design and swapped 2016 and election, so that the branding reads Election 2016 like the social cards. I confirmed with Meg that we do not need to add the check mark to the nav branding.
