### ISSUE TITLE
footer overlaps big board legend

### ISSUE THREAD

**Issue by eads** [nprapps/elections16graphics#210]
![like a fixed footer, but when you didn't want a fixed footer](https://www.dropbox.com/s/hf1czgr6bs4gqjs/Screenshot%202016-11-06%2020.40.48.png?dl=1)

**Comment by eads** [comment]
Seems to be more universal, even weirder when window is kinda short.  This is safari:

![this is in safari](https://www.dropbox.com/s/n4wstruyu79diog/Screenshot%202016-11-06%2020.42.36.png?dl=1)

**Comment by eads** [comment]
chrome too

**Comment by alykat** [comment]
Related to #155?

**Comment by eads** [comment]
related to #155

**Comment by eads** [comment]
and on my android phone
