### ISSUE TITLE
can we put in a 9pm e.t. (continued) on house? 

### ISSUE THREAD

**Issue by eads** [nprapps/elections16graphics#213]
![it's a little weird](https://www.dropbox.com/s/f399kzzzf6vv0sb/Screenshot%202016-11-06%2021.08.04.png?dl=1)

**Comment by TylerFisher** [comment]
Probably.

**Comment by TylerFisher** [comment]
<img width="1404" alt="screen shot 2016-11-06 at 9 13 48 pm" src="https://cloud.githubusercontent.com/assets/1077075/20044348/07dde5ce-a466-11e6-8c86-2f5fad4b03d6.png">

**Comment by TylerFisher** [comment]
Put this on a branch: https://github.com/nprapps/elections16graphics/tree/continued-column-header

**Comment by alykat** [comment]
Looks fine to me. Will need to make sure it's hidden on mobile.

**Comment by TylerFisher** [comment]
I checked for that. Merged and closing.
