### ISSUE TITLE
Story page widget: Electoral totals, BOP, simple navigation

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#25]

**Comment by lindamood** [comment]
Here's a wireframe of the simple nav. I suggest removing the state nav from the list of available options.

<img width="250" alt="election-macro-view__macro_view" src="https://cloud.githubusercontent.com/assets/1319852/19901063/26d221e4-a03c-11e6-9d0c-fb87b929c2a2.png">

**Comment by alykat** [comment]
pretty much done. gonna close this b/c we have separate tickets for representing expected results #76 and third-party electoral votes #41.
