### ISSUE TITLE
Big Board (House): Show district numbers

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#65]
A la 2014, where the district number was next to the state abbr:

![image](https://cloud.githubusercontent.com/assets/491318/19665596/bd87cd5c-9a13-11e6-89df-59faff072b13.png)

**Comment by TylerFisher** [comment]
Already done

![screen shot 2016-10-24 at 6 01 43 pm](https://cloud.githubusercontent.com/assets/1077075/19665635/f70f3d3a-9a13-11e6-84f8-cf6fe700ea21.png)
