### ISSUE TITLE
don't open results nav links in a new window

### ISSUE THREAD

**Issue by lindamood** [nprapps/elections16graphics#72]
Is the default for pym.js target_blank?

**Comment by TylerFisher** [comment]
It's hardcoded in the template here: https://github.com/nprapps/elections16graphics/blob/master/templates/_base_child.html#L12

**Comment by alykat** [comment]
We can change the base target to `_top` if it makes more sense for our purposes here. But we do need to set some base target so that links don't open in the iframe.
