### ISSUE TITLE
Balance of Power: Represent current called races vs. expected/safe outcomes

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#76]
Related: https://github.com/nprapps/elections16-general/issues/46

**Comment by TylerFisher** [comment]
Need a spreadsheet from Domenico, confirmation from Beth/Memmott

**Comment by alykat** [comment]
Got the OK from Beth/Memmott. Have asked Domenico for the categorizations.

**Comment by TylerFisher** [comment]
In the data, assigning to @alykat to get in the BOP graphic
