### ISSUE TITLE
Create a new factlist/quotable template using this provisional design.

### ISSUE THREAD

**Issue by lindamood** [nprapps/elections16graphics#82]
font: Knockout 30 Junior Welterweight

red: #E6221C
blue #3151A2

![general-election-wireframes__social_cards](https://cloud.githubusercontent.com/assets/1319852/19782725/1666293c-9c5d-11e6-88f9-18c4e9e6edd2.png)

**Comment by eads** [comment]
http://stage-apps.npr.org/lunchbox/quotable/index.html

**Comment by eads** [comment]
It's in a branch -- once we get final assets, we can merge it in.
