### ISSUE TITLE
Nav: When embedded on a story page, the mobile version of the nav is shown

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#85]
![image](https://cloud.githubusercontent.com/assets/491318/19789561/9e8f3c38-9c7e-11e6-88dd-4e01a0ff69fe.png)

Possible to adjust the breakpoint?

**Comment by lindamood** [comment]
We're going to move the state results into the multimedia page template to address this issue. That leaves the results map as the only results view that may live in a story page template. The results map will be using a state selectbox on mobile, in lieu of the results nav. So, I think we're good.

**Comment by lindamood** [comment]
Never mind, we need the nav on a story page for the live blog.

**Comment by lindamood** [comment]
Notes on adjustments:
- [ ] Logo
- [ ]  padding
- [ ] Narrower breakpoint 
- [ ] State nav icon right margin 
- [ ]  Tablet test
