### ISSUE TITLE
"Other" winner determination can't be simply based on percentage.

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections16graphics#93]

**Comment by TylerFisher** [comment]
Talk with Domenico about how to handle this

**Comment by alykat** [comment]
To accommodate additional (or longer) column take a look at the way column headers flipped for mobile in the [delegate tracker](http://www.npr.org/2016/03/02/468641509/elections-2016-democratic-and-republican-delegate-tracker):

https://github.com/nprapps/graphics-archive/blob/master/2016/03/delegates-20160215/css/graphic.less#L343-L365

https://twitter.com/alykat/status/710243019153350656
